stages:
  - test
  - buildcontainer
  - kubercreate
  - removefromrepository

test-branch:
  stage: test
  script:
    - echo "test"

buildcontainer-branch:
  stage: buildcontainer
  when: manual
  script:
    - echo "buildcontainer"
    - chmod +x build.sh
    - LTAG=$(echo $CI_COMMIT_BRANCH | cut -c 1-3)
    - echo $LTAG
    - ./build.sh "data-catalog" $LTAG "dev" 8080


kubercreate-branch:
  stage: kubercreate
  when: manual
  script:
    - |
      [ -z "$(kubectl get --no-headers=true deployment -l=app=data-catalog-web -o name | awk -F "/" '{print $2}'t)" ] || kubectl delete deployment data-catalog
    - |
      [ -z "$(kubectl get --no-headers=true services -l=app=data-catalog-nodeport -o name | awk -F "/" '{print $2}'t)" ] || kubectl delete service dc-service

    - kubectl create -f ./deployment/02_dc.yaml
#    - kubectl create -f ./deployment/03_dcservice.yaml
    - kubectl expose deployment data-catalog -l app=data-catalog-nodeport --type=NodePort --name=dc-service
    - kubectl describe service dc-service
    - sleep 60
#    - kubectl logs $(kubectl get --no-headers=true pods -l=app=data-catalog-web -o name | awk -F "/" '{print $2}') > kuberstdout.log
#    - kubectl cp $(kubectl get --no-headers=true pods -l=app=data-catalog-web -o name | awk -F "/" '{print $2}'):/var/logs ./logs
    - |
      #!/bin/bash
      mkdir -p ./logs
      for var in $(kubectl get --no-headers=true pods -l=app=data-catalog-web -o name | awk -F "/" '{print $2}')
      do
        echo " $var"
        kubectl logs $var > ./logs/$var.log
        kubectl cp $var:/var/logs ./logs/$var
      done
      ls ./logs

  artifacts:
    paths:
      - logs
    expire_in: 1 week

removefromrepository-branch:
  stage: removefromrepository
  when: manual
  script:
    - docker rmi 10.50.4.110:5000/data-catalog:dev
    