apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: dwh-data-catalog
    app: data-catalog-web
  name: data-catalog
#  namespace: dwh-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: dwh-data-catalog
      app: data-catalog-web  
      tier: frontend
      track: stable      
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dwh-data-catalog
        app: data-catalog-web  
        tier: frontend
        track: stable      
    spec:
      containers:
      - env:
        - name: NEO4J_CONNECTION_STRING
          value: bolt://10.50.4.110:7687
        - name: LOG_DIR
          value: /var/logs
        - name: SERVICE_PORT
          value: "8080"
        image: 10.50.4.110:5000/data-catalog:dev
        imagePullPolicy: Always
        name: data-catalog
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: repositorycred
#      restartPolicy: OnFailure

