apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: dwh-data-catalog
    app: data-catalog-web
  name: data-catalog
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: dwh-data-catalog
      app: data-catalog-web  
      tier: frontend
      track: stable      
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dwh-data-catalog
        app: data-catalog-web  
        tier: frontend
        track: stable      
    spec:
      volumes:
      - name: volumelogs
        hostPath:
          path: /mnt/logs

      containers:
      - env:
        - name: LOG_DIR
          value: /var/log/n3dwh/
        image: 10.50.4.110:5000/data-catalog:dev
        imagePullPolicy: Always
        name: data-catalog
        ports:
        - containerPort: 8080
        volumeMounts:
          - mountPath: /var/log/n3dwh/
            name: volumelogs        
      imagePullSecrets:
        - name: repositorycred
---
apiVersion: v1
kind: Service
metadata:
  name: data-catalog
  labels:
    app: data-catalog-web
spec:
  clusterIP: None
  ports:
   - name: http
     protocol: TCP
     port: 8000
  selector:
   app: data-catalog-web
