apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: dwh-data-catalog
    app: data-catalog-web
  name: data-catalog
#  namespace: dwh-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: dwh-data-catalog
      app: data-catalog-web  
      tier: frontend
      track: stable      
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dwh-data-catalog
        app: data-catalog-web  
        tier: frontend
        track: stable      
    spec:
      containers:
      - env:
        - name: dwh_data_catalog_neo4j_connection_string
          value: neo4j://10.50.4.110:7687
        - name: LOG_DIR
          value: /var/logs
        image: 10.50.4.110:5000/data-catalog:dev
        imagePullPolicy: Always
        name: data-catalog
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: repositorycred
      hostAliases:
        - ip: 127.0.0.1        
          hostnames:
          - data-catalog.lan            
#      restartPolicy: OnFailure

