"""relations

Revision ID: 0214e34358f0
Revises: b80eb6760982
Create Date: 2023-06-26 11:40:06.362012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0214e34358f0'
down_revision = 'b80eb6760982'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_relations', sa.Column('operation_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'model_relations', 'operations', ['operation_id'], ['operation_id'])
    op.drop_column('model_relations', 'function')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_relations', sa.Column('function', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'model_relations', type_='foreignkey')
    op.drop_column('model_relations', 'operation_id')
    # ### end Alembic commands ###
