"""model version table

Revision ID: 07d2d0ea766a
Revises: 11249d09c953
Create Date: 2023-05-19 17:11:42.774435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07d2d0ea766a'
down_revision = '11249d09c953'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
