"""renamed columns

Revision ID: 08bcf434e18e
Revises: ad5440498d8d
Create Date: 2023-05-23 10:03:04.632390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08bcf434e18e'
down_revision = 'ad5440498d8d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('short_desc', sa.Text(), nullable=True))
    op.add_column('models', sa.Column('business_desc', sa.Text(), nullable=True))
    op.drop_column('models', 'desc')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('desc', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('models', 'business_desc')
    op.drop_column('models', 'short_desc')
    # ### end Alembic commands ###
