"""model table

Revision ID: 11249d09c953
Revises: 394c2a025036
Create Date: 2023-05-19 13:31:12.621027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11249d09c953'
down_revision = '394c2a025036'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('owner', sa.String(length=144), nullable=False),
    sa.Column('desc', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_models_guid'), 'models', ['guid'], unique=True)
    op.create_table('model_tags',
    sa.Column('model_tags', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['model_tags'], ['models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('model_tags', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_tags')
    op.drop_index(op.f('ix_models_guid'), table_name='models')
    op.drop_table('models')
    # ### end Alembic commands ###
