"""Converted log_name field to Text type. Exceded event length to 100 in logs table

Revision ID: 123f51673778
Revises: 4dbf0c6c04b8
Create Date: 2023-08-28 13:01:49.574038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '123f51673778'
down_revision = '4dbf0c6c04b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logs', 'log_name',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('logs', 'event',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logs', 'event',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('logs', 'log_name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###
