"""created queries, query_executions, query_viewers, query_tags and query_query_viewers. Plus deleted query_construct and all linked to it tables

Revision ID: 14876b673588
Revises: dedf62b4d42a
Create Date: 2023-07-18 11:01:01.624536

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '14876b673588'
down_revision = 'dedf62b4d42a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_viewers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('guid', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid')
    )
    op.create_index(op.f('ix_query_viewers_id'), 'query_viewers', ['id'], unique=True)
    op.create_table('queries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('guid', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('json', sa.JSON(), nullable=False),
    sa.Column('owner_guid', sa.String(length=100), nullable=False),
    sa.Column('model_version_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queries_guid'), 'queries', ['guid'], unique=True)
    op.create_index(op.f('ix_queries_id'), 'queries', ['id'], unique=True)
    op.create_table('query_executions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('guid', sa.String(length=100), nullable=False),
    sa.Column('query_id', sa.BigInteger(), nullable=False),
    sa.Column('query_run_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('status_updated_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('publish_name', sa.String(length=500), nullable=True),
    sa.Column('publish_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_executions_guid'), 'query_executions', ['guid'], unique=True)
    op.create_index(op.f('ix_query_executions_id'), 'query_executions', ['id'], unique=True)
    op.create_table('query_query_viewers',
    sa.Column('query_id', sa.BigInteger(), nullable=False),
    sa.Column('viewer_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ),
    sa.ForeignKeyConstraint(['viewer_id'], ['query_viewers.id'], ),
    sa.PrimaryKeyConstraint('query_id', 'viewer_id')
    )
    op.create_table('query_tags',
    sa.Column('query_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('query_id', 'tag_id')
    )
    op.drop_index('ix_query_constructor_body_fields_guid', table_name='query_constructor_body_fields')
    op.drop_table('query_constructor_body_fields')

    op.drop_index('ix_query_constructor_reviewers_guid', table_name='query_constructor_reviewers')
    op.drop_table('query_constructor_reviewers')

    op.drop_index('ix_query_constructor_bodies_guid', table_name='query_constructor_bodies')
    op.drop_table('query_constructor_bodies')

    op.drop_index('ix_query_constructor_history_guid', table_name='query_constructor_history')
    op.drop_table('query_constructor_history')

    op.drop_table('query_constructor_tags')

    op.drop_index('ix_query_constructors_guid', table_name='query_constructors')
    op.drop_table('query_constructors')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_constructor_tags',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['query_constructors.id'], name='query_constructor_tags_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name='query_constructor_tags_tag_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'tag_id', name='query_constructor_tags_pkey')
    )
    op.create_table('query_constructor_body_fields',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('guid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('model_resource_attribute_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('query_constructor_body_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['model_resource_attribute_id'], ['model_resource_attributes.id'], name='query_constructor_body_fields_model_resource_attribute_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['query_constructor_body_id'], ['query_constructor_bodies.id'], name='query_constructor_body_fields_query_constructor_body_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='query_constructor_body_fields_pkey')
    )
    op.create_index('ix_query_constructor_body_fields_guid', 'query_constructor_body_fields', ['guid'], unique=False)
    op.create_table('query_constructor_history',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('guid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('query_constructor_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('ended_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['query_constructor_id'], ['query_constructors.id'], name='query_constructor_history_query_constructor_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='query_constructor_history_pkey')
    )
    op.create_index('ix_query_constructor_history_guid', 'query_constructor_history', ['guid'], unique=False)
    op.create_table('query_constructor_reviewers',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('guid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('query_constructor_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['query_constructor_id'], ['query_constructors.id'], name='query_constructor_reviewers_query_constructor_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='query_constructor_reviewers_pkey')
    )
    op.create_index('ix_query_constructor_reviewers_guid', 'query_constructor_reviewers', ['guid'], unique=False)
    op.create_table('query_constructors',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('query_constructors_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('guid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('owner', sa.VARCHAR(length=144), autoincrement=False, nullable=False),
    sa.Column('desc', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='query_constructors_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_query_constructors_guid', 'query_constructors', ['guid'], unique=False)
    op.create_table('query_constructor_bodies',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('guid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('query_constructor_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('model_version_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('aggregators', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], name='query_constructor_bodies_model_version_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['query_constructor_id'], ['query_constructors.id'], name='query_constructor_bodies_query_constructor_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='query_constructor_bodies_pkey')
    )
    op.create_index('ix_query_constructor_bodies_guid', 'query_constructor_bodies', ['guid'], unique=False)
    op.drop_table('query_tags')
    op.drop_table('query_query_viewers')
    op.drop_index(op.f('ix_query_executions_id'), table_name='query_executions')
    op.drop_index(op.f('ix_query_executions_guid'), table_name='query_executions')
    op.drop_table('query_executions')
    op.drop_index(op.f('ix_queries_id'), table_name='queries')
    op.drop_index(op.f('ix_queries_guid'), table_name='queries')
    op.drop_table('queries')
    op.drop_index(op.f('ix_query_viewers_id'), table_name='query_viewers')
    op.drop_table('query_viewers')
    # ### end Alembic commands ###
