"""added on delete cascade to object_guid fk in fields table

Revision ID: 1b99ac0a9107
Revises: b5b9948dad32
Create Date: 2023-06-21 12:16:29.410794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b99ac0a9107'
down_revision = 'b5b9948dad32'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fields_object_guid_fkey', 'fields', type_='foreignkey')
    op.create_foreign_key(None, 'fields', 'objects', ['object_guid'], ['guid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fields', type_='foreignkey')
    op.create_foreign_key('fields_object_guid_fkey', 'fields', 'objects', ['object_guid'], ['guid'])
    # ### end Alembic commands ###
