"""Create relation

Revision ID: 1bfcf88db635
Revises: 64580ed0d3e7
Create Date: 2023-06-05 13:43:16.127189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bfcf88db635'
down_revision = '64580ed0d3e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('quality_guid', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'comments', 'model_qualities', ['quality_guid'], ['guid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'quality_guid')
    # ### end Alembic commands ###
