"""added cascade on delete to query_query_viewers table

Revision ID: 2b4b7345dbde
Revises: 46e2b611a0bd
Create Date: 2023-07-27 16:28:02.375187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b4b7345dbde'
down_revision = '46e2b611a0bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('query_query_viewers_viewer_id_fkey', 'query_query_viewers', type_='foreignkey')
    op.drop_constraint('query_query_viewers_query_id_fkey', 'query_query_viewers', type_='foreignkey')
    op.create_foreign_key(None, 'query_query_viewers', 'queries', ['query_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'query_query_viewers', 'query_viewers', ['viewer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'query_query_viewers', type_='foreignkey')
    op.drop_constraint(None, 'query_query_viewers', type_='foreignkey')
    op.create_foreign_key('query_query_viewers_query_id_fkey', 'query_query_viewers', 'queries', ['query_id'], ['id'])
    op.create_foreign_key('query_query_viewers_viewer_id_fkey', 'query_query_viewers', 'query_viewers', ['viewer_id'], ['id'])
    # ### end Alembic commands ###
