"""renamed is_synchronized on is_synchronizing in objects table

Revision ID: 2ee335540c3e
Revises: 4829f32490be
Create Date: 2023-06-16 17:26:11.026685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ee335540c3e'
down_revision = '4829f32490be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objects', sa.Column('is_synchronizing', sa.Boolean(), nullable=False))
    op.drop_column('objects', 'is_synchronized')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objects', sa.Column('is_synchronized', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('objects', 'is_synchronizing')
    # ### end Alembic commands ###
