"""remove_relation_groups

Revision ID: 2ef9f53a4124
Revises: a41df1f3e685
Create Date: 2023-07-03 09:10:34.601250

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2ef9f53a4124'
down_revision = 'a41df1f3e685'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_model_relation_groups_guid', table_name='model_relation_groups')
    op.drop_constraint('model_attitudes_right_attribute_id_fkey', 'model_attitudes', type_='foreignkey')
    op.drop_constraint('model_attitudes_left_attribute_id_fkey', 'model_attitudes', type_='foreignkey')
    op.create_foreign_key(None, 'model_attitudes', 'model_resource_attributes', ['left_attribute_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'model_attitudes', 'model_resource_attributes', ['right_attribute_id'], ['id'], ondelete='CASCADE')
    op.add_column('model_relations', sa.Column('model_version_id', sa.BigInteger(), nullable=True))
    op.drop_constraint('model_relations_model_relation_group_id_fkey', 'model_relations', type_='foreignkey')
    op.create_foreign_key(None, 'model_relations', 'model_versions', ['model_version_id'], ['id'], ondelete='CASCADE')
    op.drop_column('model_relations', 'model_relation_group_id')
    op.drop_constraint('model_resource_attributes_model_resource_id_fkey', 'model_resource_attributes', type_='foreignkey')
    op.drop_constraint('model_resource_attributes_model_data_type_id_fkey', 'model_resource_attributes', type_='foreignkey')
    op.create_foreign_key(None, 'model_resource_attributes', 'model_data_types', ['model_data_type_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'model_resource_attributes', 'model_resources', ['model_resource_id'], ['id'], ondelete='CASCADE')
    op.drop_table('model_relation_group_tags')
    op.drop_table('model_relation_groups')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'model_resource_attributes', type_='foreignkey')
    op.drop_constraint(None, 'model_resource_attributes', type_='foreignkey')
    op.create_foreign_key('model_resource_attributes_model_data_type_id_fkey', 'model_resource_attributes', 'model_data_types', ['model_data_type_id'], ['id'])
    op.create_foreign_key('model_resource_attributes_model_resource_id_fkey', 'model_resource_attributes', 'model_resources', ['model_resource_id'], ['id'])
    op.add_column('model_relations', sa.Column('model_relation_group_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'model_relations', type_='foreignkey')
    op.create_foreign_key('model_relations_model_relation_group_id_fkey', 'model_relations', 'model_relation_groups', ['model_relation_group_id'], ['id'], ondelete='CASCADE')
    op.drop_column('model_relations', 'model_version_id')
    op.drop_constraint(None, 'model_attitudes', type_='foreignkey')
    op.drop_constraint(None, 'model_attitudes', type_='foreignkey')
    op.create_foreign_key('model_attitudes_left_attribute_id_fkey', 'model_attitudes', 'model_resource_attributes', ['left_attribute_id'], ['id'])
    op.create_foreign_key('model_attitudes_right_attribute_id_fkey', 'model_attitudes', 'model_resource_attributes', ['right_attribute_id'], ['id'])
    op.create_table('model_relation_groups',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('model_relation_groups_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('guid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('model_version_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('owner', sa.VARCHAR(length=144), autoincrement=False, nullable=False),
    sa.Column('desc', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], name='model_relation_groups_model_version_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='model_relation_groups_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_model_relation_groups_guid', 'model_relation_groups', ['guid'], unique=False)
    op.create_table('model_relation_group_tags',
    sa.Column('model_relation_group_tags', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['model_relation_group_tags'], ['model_relation_groups.id'], name='model_relation_group_tags_model_relation_group_tags_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name='model_relation_group_tags_tag_id_fkey'),
    sa.PrimaryKeyConstraint('model_relation_group_tags', 'tag_id', name='model_relation_group_tags_pkey')
    )
    # ### end Alembic commands ###
