"""run_query

Revision ID: 38c3d0f43b81
Revises: a1a631551763
Create Date: 2023-06-23 11:43:53.116461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38c3d0f43b81'
down_revision = 'a1a631551763'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query_constructor_history', 'status')
    op.add_column('query_constructor_history', sa.Column('status', sa.Integer(), nullable=False))
    op.add_column('query_constructors', sa.Column('status', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query_constructors', 'status')
    op.drop_column('query_constructor_history', 'status')
    op.add_column('query_constructor_history', sa.Column('status', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
