"""new columns

Revision ID: 46e2b611a0bd
Revises: 9a0ed6f0d3c5
Create Date: 2023-07-26 11:37:08.614070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46e2b611a0bd'
down_revision = '9a0ed6f0d3c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries', sa.Column('filters_displayed', sa.Text(), nullable=False))
    op.add_column('queries', sa.Column('having_displayed', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queries', 'having_displayed')
    op.drop_column('queries', 'filters_displayed')
    # ### end Alembic commands ###
