"""removed status column

Revision ID: 48188628f9b9
Revises: 4856ec8d43bd
Create Date: 2023-05-26 10:35:49.020386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48188628f9b9'
down_revision = '4856ec8d43bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_versions', sa.Column('version', sa.String(length=100), nullable=False))
    op.drop_column('model_versions', 'name')
    op.drop_column('model_versions', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_versions', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('model_versions', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('model_versions', 'version')
    # ### end Alembic commands ###
