"""linked models to source_registries, substituted column type for column data_type_id

Revision ID: 4829f32490bc
Revises: cb32eb3979ad
Create Date: 2023-06-09 16:50:23.780047

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4829f32490bc'
down_revision = 'cb32eb3979ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=36), nullable=False),
    sa.Column('log_name', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('identity_id', sa.String(length=36), nullable=False),
    sa.Column('event', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_identity_id'), 'logs', ['identity_id'], unique=False)
    op.create_index(op.f('ix_logs_log_name'), 'logs', ['log_name'], unique=False)
    op.create_index(op.f('ix_logs_type'), 'logs', ['type'], unique=False)
    op.add_column('fields', sa.Column('data_type_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_fields_data_type_id'), 'fields', ['data_type_id'], unique=False)
    op.drop_column('fields', 'type')
    op.add_column('models', sa.Column('source_registry_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'models', 'source_registers', ['source_registry_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'models', type_='foreignkey')
    op.drop_column('models', 'source_registry_id')
    op.add_column('fields', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_fields_data_type_id'), table_name='fields')
    op.drop_column('fields', 'data_type_id')
    op.drop_index(op.f('ix_logs_type'), table_name='logs')
    op.drop_index(op.f('ix_logs_log_name'), table_name='logs')
    op.drop_index(op.f('ix_logs_identity_id'), table_name='logs')
    op.drop_table('logs')
    # ### end Alembic commands ###
