"""deleted_at column

Revision ID: 4dbf0c6c04b8
Revises: 7e9f475eec7d
Create Date: 2023-08-28 08:22:47.166047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dbf0c6c04b8'
down_revision = '7e9f475eec7d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'deleted_at')
    # ### end Alembic commands ###
