"""operations 2

Revision ID: 510169d4ab11
Revises: 03b0641bd098
Create Date: 2023-06-19 12:50:36.788228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '510169d4ab11'
down_revision = '03b0641bd098'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation_bodies', sa.Column('operation_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'operation_bodies', 'operations', ['operation_id'], ['operation_id'], ondelete='CASCADE')
    op.drop_constraint('operations_operation_body_id_fkey', 'operations', type_='foreignkey')
    op.drop_column('operations', 'operation_body_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operations', sa.Column('operation_body_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key('operations_operation_body_id_fkey', 'operations', 'operation_bodies', ['operation_body_id'], ['operation_body_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'operation_bodies', type_='foreignkey')
    op.drop_column('operation_bodies', 'operation_id')
    # ### end Alembic commands ###
