"""source registry and tags relationship changed many-to-many, owner string can have 36*3 characters, added new column in source_registries table called is_synchronized

Revision ID: 5ad8809614ca
Revises: af8c000c166c
Create Date: 2023-04-27 14:13:36.391673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ad8809614ca'
down_revision = 'af8c000c166c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_registry_tags',
    sa.Column('source_registry_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['source_registry_id'], ['source_registers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('source_registry_id', 'tag_id')
    )
    op.add_column('source_registers', sa.Column('is_synchronized', sa.Boolean(), nullable=False))
    op.drop_constraint('tags_source_guid_fkey', 'tags', type_='foreignkey')
    op.drop_column('tags', 'source_guid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('source_guid', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.create_foreign_key('tags_source_guid_fkey', 'tags', 'source_registers', ['source_guid'], ['guid'], ondelete='CASCADE')
    op.drop_column('source_registers', 'is_synchronized')
    op.drop_table('source_registry_tags')
    # ### end Alembic commands ###
