"""added json and xml fields to model_resources table

Revision ID: 5c9927192a4e
Revises: 0214e34358f0
Create Date: 2023-06-27 12:42:34.766915

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5c9927192a4e'
down_revision = '0214e34358f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_resources', sa.Column('json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('model_resources', sa.Column('xml', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_resources', 'xml')
    op.drop_column('model_resources', 'json')
    # ### end Alembic commands ###
