"""operation version tags

Revision ID: 5d75716ffcc7
Revises: 70fd15a28ed0
Create Date: 2023-07-19 14:04:06.232494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d75716ffcc7'
down_revision = '70fd15a28ed0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation_body_tags',
    sa.Column('operation_body_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['operation_body_id'], ['operation_bodies.operation_body_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('operation_body_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operation_body_tags')
    # ### end Alembic commands ###
