"""Create relation

Revision ID: 64580ed0d3e7
Revises: 817d6c09dc3e
Create Date: 2023-06-05 08:18:32.067015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64580ed0d3e7'
down_revision = '817d6c09dc3e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_resources',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('model_version_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('owner', sa.String(length=144), nullable=False),
    sa.Column('desc', sa.String(length=500), nullable=True),
    sa.Column('type', sa.String(length=500), nullable=True),
    sa.Column('db_link', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_resources_guid'), 'model_resources', ['guid'], unique=True)
    op.create_table('model_resource_tags',
    sa.Column('model_resource_tags', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['model_resource_tags'], ['model_resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('model_resource_tags', 'tag_id')
    )
    op.add_column('comments', sa.Column('resource_guid', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'comments', 'model_resources', ['resource_guid'], ['guid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'resource_guid')
    op.drop_table('model_resource_tags')
    op.drop_index(op.f('ix_model_resources_guid'), table_name='model_resources')
    op.drop_table('model_resources')
    # ### end Alembic commands ###
