"""operations

Revision ID: 70fd15a28ed0
Revises: 14876b673588
Create Date: 2023-07-19 12:32:52.079899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70fd15a28ed0'
down_revision = '14876b673588'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation_bodies', sa.Column('owner', sa.String(length=144), nullable=True))
    op.add_column('operation_bodies', sa.Column('desc', sa.String(length=1000), nullable=True))
    op.add_column('operation_bodies', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_column('operation_bodies', 'version_desc')
    op.drop_column('operation_bodies', 'version_owner')
    op.add_column('operation_body_parameters', sa.Column('display_name', sa.String(length=200), nullable=False))
    op.drop_column('operation_body_parameters', 'name_for_relation')
    op.drop_column('operations', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operations', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('operation_body_parameters', sa.Column('name_for_relation', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_column('operation_body_parameters', 'display_name')
    op.add_column('operation_bodies', sa.Column('version_owner', sa.VARCHAR(length=144), autoincrement=False, nullable=True))
    op.add_column('operation_bodies', sa.Column('version_desc', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.drop_column('operation_bodies', 'updated_at')
    op.drop_column('operation_bodies', 'desc')
    op.drop_column('operation_bodies', 'owner')
    # ### end Alembic commands ###
