"""activity log table'


Revision ID: 80430efcd9ee
Revises: 85510f0ddbf1
Create Date: 2023-05-04 14:46:37.510289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80430efcd9ee'
down_revision = '85510f0ddbf1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
