"""dropped indexes and increased owner size column to 36*4

Revision ID: 85510f0ddbf1
Revises: c2f2c4417b06
Create Date: 2023-05-02 13:47:56.693186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85510f0ddbf1'
down_revision = 'c2f2c4417b06'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_comments_msg', table_name='comments')
    op.alter_column('source_registers', 'owner',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=144),
               existing_nullable=False)
    op.drop_index('ix_source_registers_desc', table_name='source_registers')
    op.drop_index('ix_source_registers_name', table_name='source_registers')
    op.create_unique_constraint(None, 'source_registers', ['name'])
    op.drop_index('ix_tags_name', table_name='tags')
    op.create_unique_constraint(None, 'tags', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='unique')
    op.create_index('ix_tags_name', 'tags', ['name'], unique=False)
    op.drop_constraint(None, 'source_registers', type_='unique')
    op.create_index('ix_source_registers_name', 'source_registers', ['name'], unique=False)
    op.create_index('ix_source_registers_desc', 'source_registers', ['desc'], unique=False)
    op.alter_column('source_registers', 'owner',
               existing_type=sa.String(length=144),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.create_index('ix_comments_msg', 'comments', ['msg'], unique=False)
    # ### end Alembic commands ###
