"""data types

Revision ID: 85b481f7b6f7
Revises: 8aa097dd7e70
Create Date: 2023-05-26 14:25:44.114420

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '85b481f7b6f7'
down_revision = '8aa097dd7e70'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_data_types',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('desc', sa.String(length=500), nullable=True),
    sa.Column('json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('xml', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_data_types')
    # ### end Alembic commands ###
