"""attributes

Revision ID: 8923a129b2e9
Revises: ba5c91b7ab06
Create Date: 2023-06-26 06:30:23.858558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8923a129b2e9'
down_revision = 'ba5c91b7ab06'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('model_resource_attributes', 'cardinality',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('model_resource_attributes', 'cardinality',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
