"""Create attitude

Revision ID: 899d03d2910a
Revises: 1bfcf88db635
Create Date: 2023-06-05 14:01:00.640998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '899d03d2910a'
down_revision = '1bfcf88db635'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_attitudes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('resource_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['model_resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_attitudes_guid'), 'model_attitudes', ['guid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_attitudes_guid'), table_name='model_attitudes')
    op.drop_table('model_attitudes')
    # ### end Alembic commands ###
