"""Create relation2

Revision ID: 89dc1f0baaf8
Revises: 93c1f1e5bf34
Create Date: 2023-06-01 12:59:47.926106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89dc1f0baaf8'
down_revision = '93c1f1e5bf34'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_relation_group_tags',
    sa.Column('model_relation_group_tags', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['model_relation_group_tags'], ['model_relation_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('model_relation_group_tags', 'tag_id')
    )
    op.create_table('model_relation_tags',
    sa.Column('model_relation_tags', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['model_relation_tags'], ['model_relations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('model_relation_tags', 'tag_id')
    )
    op.drop_constraint('model_relation_groups_model_version_id_fkey', 'model_relation_groups', type_='foreignkey')
    op.create_foreign_key(None, 'model_relation_groups', 'model_versions', ['model_version_id'], ['id'])
    op.add_column('model_relations', sa.Column('model_relation_group_id', sa.BigInteger(), nullable=True))
    op.drop_constraint('model_relations_relation_group_id_fkey', 'model_relations', type_='foreignkey')
    op.create_foreign_key(None, 'model_relations', 'model_relation_groups', ['model_relation_group_id'], ['id'])
    op.drop_column('model_relations', 'relation_group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_relations', sa.Column('relation_group_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'model_relations', type_='foreignkey')
    op.create_foreign_key('model_relations_relation_group_id_fkey', 'model_relations', 'models', ['relation_group_id'], ['id'])
    op.drop_column('model_relations', 'model_relation_group_id')
    op.drop_constraint(None, 'model_relation_groups', type_='foreignkey')
    op.create_foreign_key('model_relation_groups_model_version_id_fkey', 'model_relation_groups', 'models', ['model_version_id'], ['id'])
    op.drop_table('model_relation_tags')
    op.drop_table('model_relation_group_tags')
    # ### end Alembic commands ###
