"""status added

Revision ID: 8aa097dd7e70
Revises: 7eb23c7206e9
Create Date: 2023-05-26 13:04:24.084749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aa097dd7e70'
down_revision = '7eb23c7206e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_versions', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_versions', 'status')
    # ### end Alembic commands ###
