"""data types add fields

Revision ID: 8def9138fd26
Revises: 7f2c3361d2bb
Create Date: 2023-06-06 14:08:27.557774

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8def9138fd26'
down_revision = '7f2c3361d2bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_data_types', sa.Column('additional', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('model_data_types', sa.Column('comments', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_data_types', 'comments')
    op.drop_column('model_data_types', 'additional')
    # ### end Alembic commands ###
