"""operation versions

Revision ID: 953728de927a
Revises: e344a6dc8960
Create Date: 2023-07-04 14:47:04.271540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '953728de927a'
down_revision = 'e344a6dc8960'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation_bodies', sa.Column('version', sa.BigInteger(), nullable=True))
    op.add_column('operation_bodies', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('operation_bodies', sa.Column('version_owner', sa.String(length=144), nullable=True))
    op.add_column('operation_bodies', sa.Column('version_desc', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operation_bodies', 'version_desc')
    op.drop_column('operation_bodies', 'version_owner')
    op.drop_column('operation_bodies', 'created_at')
    op.drop_column('operation_bodies', 'version')
    # ### end Alembic commands ###
