"""log table

Revision ID: 994e7414cb6a
Revises: 85510f0ddbf1
Create Date: 2023-05-15 16:35:10.573007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '994e7414cb6a'
down_revision = '85510f0ddbf1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
