"""added description columnt to logs table

Revision ID: 9a0ed6f0d3c5
Revises: ecc020d3e30f
Create Date: 2023-07-25 15:11:30.815240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a0ed6f0d3c5'
down_revision = 'ecc020d3e30f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'description')
    # ### end Alembic commands ###
