"""remove data types comments

Revision ID: 9b4dba61f79a
Revises: cc212b26c80b
Create Date: 2023-06-08 09:24:46.812986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b4dba61f79a'
down_revision = 'cc212b26c80b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_data_types', 'comments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_data_types', sa.Column('comments', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
