"""resource_desc

Revision ID: a1a631551763
Revises: da8c906422ff
Create Date: 2023-06-23 06:11:59.001707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1a631551763'
down_revision = 'da8c906422ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('model_resources', 'desc',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('model_resources', 'desc',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
