"""model resource attributes

Revision ID: b38f24431da7
Revises: 9b4dba61f79a
Create Date: 2023-06-08 11:44:36.878455

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b38f24431da7'
down_revision = '9b4dba61f79a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_resource_attributes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('resource_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key', sa.Boolean(), nullable=True),
    sa.Column('db_link', sa.String(length=500), nullable=True),
    sa.Column('desc', sa.String(length=1000), nullable=True),
    sa.Column('data_type_id', sa.BigInteger(), nullable=True),
    sa.Column('data_type_flag', sa.Integer(), nullable=True),
    sa.Column('cardinality', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['model_resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_resource_attributes_data_type_id'), 'model_resource_attributes', ['data_type_id'], unique=False)
    op.create_index(op.f('ix_model_resource_attributes_guid'), 'model_resource_attributes', ['guid'], unique=True)
    op.create_index(op.f('ix_model_resource_attributes_key'), 'model_resource_attributes', ['key'], unique=False)
    op.create_table('model_resource_attribute_tags',
    sa.Column('model_resource_attribute_tags', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['model_resource_attribute_tags'], ['model_resource_attributes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('model_resource_attribute_tags', 'tag_id')
    )
    op.add_column('model_resources', sa.Column('json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('model_resources', sa.Column('xml', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_resources', 'xml')
    op.drop_column('model_resources', 'json')
    op.drop_table('model_resource_attribute_tags')
    op.drop_index(op.f('ix_model_resource_attributes_key'), table_name='model_resource_attributes')
    op.drop_index(op.f('ix_model_resource_attributes_guid'), table_name='model_resource_attributes')
    op.drop_index(op.f('ix_model_resource_attributes_data_type_id'), table_name='model_resource_attributes')
    op.drop_table('model_resource_attributes')
    # ### end Alembic commands ###
