"""attributes_fields

Revision ID: b5b9948dad32
Revises: b3ece1bf7e0d
Create Date: 2023-06-21 11:43:04.715093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5b9948dad32'
down_revision = 'b3ece1bf7e0d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_resource_attributes', sa.Column('model_resource_id', sa.BigInteger(), nullable=True))
    op.add_column('model_resource_attributes', sa.Column('model_data_type_id', sa.BigInteger(), nullable=True))
    op.drop_index('ix_model_resource_attributes_data_type_id', table_name='model_resource_attributes')
    op.create_foreign_key(None, 'model_resource_attributes', 'model_resources', ['model_resource_id'], ['id'])
    op.create_foreign_key(None, 'model_resource_attributes', 'model_data_types', ['model_data_type_id'], ['id'])
    op.drop_column('model_resource_attributes', 'data_type_id')
    op.drop_column('model_resource_attributes', 'data_type_flag')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_resource_attributes', sa.Column('data_type_flag', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('model_resource_attributes', sa.Column('data_type_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'model_resource_attributes', type_='foreignkey')
    op.drop_constraint(None, 'model_resource_attributes', type_='foreignkey')
    op.create_index('ix_model_resource_attributes_data_type_id', 'model_resource_attributes', ['data_type_id'], unique=False)
    op.drop_column('model_resource_attributes', 'model_data_type_id')
    op.drop_column('model_resource_attributes', 'model_resource_id')
    # ### end Alembic commands ###
