"""added on delete = cascade to model_versions table

Revision ID: cc212b26c80b
Revises: 8def9138fd26
Create Date: 2023-06-07 11:38:23.531299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc212b26c80b'
down_revision = '8def9138fd26'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('model_versions_model_id_fkey', 'model_versions', type_='foreignkey')
    op.create_foreign_key(None, 'model_versions', 'models', ['model_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'model_versions', type_='foreignkey')
    op.create_foreign_key('model_versions_model_id_fkey', 'model_versions', 'models', ['model_id'], ['id'])
    # ### end Alembic commands ###
