"""confirmed at

Revision ID: d4717bf4e55b
Revises: 65ca2912225a
Create Date: 2023-05-29 11:50:19.588019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4717bf4e55b'
down_revision = '65ca2912225a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_versions', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_versions', 'confirmed_at')
    # ### end Alembic commands ###
