"""attribute fkey

Revision ID: d86fb15ef56b
Revises: affdf30945a3
Create Date: 2023-07-10 11:51:55.206374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd86fb15ef56b'
down_revision = 'affdf30945a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_model_resource_attributes_model_resource_id'), 'model_resource_attributes', ['model_resource_id'], unique=False)
    op.drop_constraint('model_resource_attributes_model_resource_id_fkey', 'model_resource_attributes', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('model_resource_attributes_model_resource_id_fkey', 'model_resource_attributes', 'model_resources', ['model_resource_id'], ['id'])
    op.drop_index(op.f('ix_model_resource_attributes_model_resource_id'), table_name='model_resource_attributes')
    # ### end Alembic commands ###
