"""desc_length

Revision ID: da8c906422ff
Revises: f95c1413e508
Create Date: 2023-06-22 14:17:29.815212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da8c906422ff'
down_revision = 'f95c1413e508'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('model_relation_groups', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('model_relation_groups', 'desc',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               nullable=False)
    op.alter_column('model_relations', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('model_relations', 'desc',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               nullable=False)
    op.alter_column('model_resource_attributes', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('model_resource_attributes', 'desc',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               nullable=False)
    op.alter_column('model_resources', 'desc',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               nullable=False)
    op.alter_column('model_versions', 'desc',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('model_versions', 'desc',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('model_resources', 'desc',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('model_resource_attributes', 'desc',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               nullable=True)
    op.alter_column('model_resource_attributes', 'name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('model_relations', 'desc',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('model_relations', 'name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('model_relation_groups', 'desc',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('model_relation_groups', 'name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
