"""access labels

Revision ID: dedf62b4d42a
Revises: 8a1ba1059dd1
Create Date: 2023-07-17 11:16:30.732354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dedf62b4d42a'
down_revision = '8a1ba1059dd1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_labels',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=15), nullable=True),
    sa.Column('operation_version_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['operation_version_id'], ['operation_bodies.operation_body_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_access_labels',
    sa.Column('model_access_labels', sa.BigInteger(), nullable=False),
    sa.Column('access_label_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['access_label_id'], ['access_labels.id'], ),
    sa.ForeignKeyConstraint(['model_access_labels'], ['models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('model_access_labels', 'access_label_id')
    )
    op.create_table('model_version_access_labels',
    sa.Column('model_version_access_labels', sa.BigInteger(), nullable=False),
    sa.Column('access_label_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['access_label_id'], ['access_labels.id'], ),
    sa.ForeignKeyConstraint(['model_version_access_labels'], ['model_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('model_version_access_labels', 'access_label_id')
    )
    op.create_table('model_resource_access_labels',
    sa.Column('model_resource_access_labels', sa.BigInteger(), nullable=False),
    sa.Column('access_label_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['access_label_id'], ['access_labels.id'], ),
    sa.ForeignKeyConstraint(['model_resource_access_labels'], ['model_resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('model_resource_access_labels', 'access_label_id')
    )
    op.create_table('model_resource_attribute_access_labels',
    sa.Column('model_resource_attribute_access_labels', sa.BigInteger(), nullable=False),
    sa.Column('access_label_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['access_label_id'], ['access_labels.id'], ),
    sa.ForeignKeyConstraint(['model_resource_attribute_access_labels'], ['model_resource_attributes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('model_resource_attribute_access_labels', 'access_label_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_resource_attribute_access_labels')
    op.drop_table('model_resource_access_labels')
    op.drop_table('model_version_access_labels')
    op.drop_table('model_access_labels')
    op.drop_table('access_labels')
    # ### end Alembic commands ###
