"""pipelines

Revision ID: e344a6dc8960
Revises: 2ef9f53a4124
Create Date: 2023-07-03 15:08:48.919459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e344a6dc8960'
down_revision = '2ef9f53a4124'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipelines',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('owner', sa.String(length=144), nullable=False),
    sa.Column('desc', sa.String(length=1000), nullable=True),
    sa.Column('model_version_id', sa.BigInteger(), nullable=True),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('base', sa.Boolean(), nullable=False),
    sa.Column('operating_mode', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipelines_guid'), 'pipelines', ['guid'], unique=True)
    op.create_index(op.f('ix_pipelines_name'), 'pipelines', ['name'], unique=True)
    op.create_table('pipeline_results',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pipeline_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.BigInteger(), nullable=False),
    sa.Column('attachment', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_tags',
    sa.Column('pipeline_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('pipeline_id', 'tag_id')
    )
    op.add_column('comments', sa.Column('pipeline_guid', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'comments', 'pipelines', ['pipeline_guid'], ['guid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'pipeline_guid')
    op.drop_table('pipeline_tags')
    op.drop_table('pipeline_results')
    op.drop_index(op.f('ix_pipelines_name'), table_name='pipelines')
    op.drop_index(op.f('ix_pipelines_guid'), table_name='pipelines')
    op.drop_table('pipelines')
    # ### end Alembic commands ###
