"""columns fixed

Revision ID: e652a28e4a9d
Revises: 48188628f9b9
Create Date: 2023-05-26 10:45:13.528491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e652a28e4a9d'
down_revision = '48188628f9b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_versions', sa.Column('status', sa.String(), nullable=False))
    op.alter_column('model_versions', 'version',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('model_versions', 'version',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('model_versions', 'status')
    # ### end Alembic commands ###
