"""added filter type into query table

Revision ID: ecc020d3e30f
Revises: 5d75716ffcc7
Create Date: 2023-07-21 12:43:41.173003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecc020d3e30f'
down_revision = '5d75716ffcc7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries', sa.Column('filter_type', sa.String(), nullable=True))
    op.create_index(op.f('ix_queries_filter_type'), 'queries', ['filter_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_queries_filter_type'), table_name='queries')
    op.drop_column('queries', 'filter_type')
    # ### end Alembic commands ###
