"""attribute resource

Revision ID: ed2190a00573
Revises: 953728de927a
Create Date: 2023-07-05 07:45:55.737646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed2190a00573'
down_revision = '953728de927a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('model_resource_attributes_model_resource_id_fkey', 'model_resource_attributes', type_='foreignkey')
    op.create_foreign_key(None, 'model_resource_attributes', 'model_resources', ['model_resource_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'model_resource_attributes', type_='foreignkey')
    op.create_foreign_key('model_resource_attributes_model_resource_id_fkey', 'model_resource_attributes', 'model_resources', ['model_resource_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
