"""model resource id added into queries

Revision ID: ed92aa8874e5
Revises: 2b4b7345dbde
Create Date: 2023-07-31 13:23:43.845575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed92aa8874e5'
down_revision = '2b4b7345dbde'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries', sa.Column('model_resource_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'queries', 'model_resources', ['model_resource_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'queries', type_='foreignkey')
    op.drop_column('queries', 'model_resource_id')
    # ### end Alembic commands ###
