"""attitude_atributes

Revision ID: f90d3ead2924
Revises: 5ef17c73918e
Create Date: 2023-06-23 12:54:05.660535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f90d3ead2924'
down_revision = '5ef17c73918e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_attitudes', sa.Column('left_attribute_id', sa.BigInteger(), nullable=True))
    op.add_column('model_attitudes', sa.Column('right_attribute_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'model_attitudes', 'model_resource_attributes', ['left_attribute_id'], ['id'])
    op.create_foreign_key(None, 'model_attitudes', 'model_resource_attributes', ['right_attribute_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'model_attitudes', type_='foreignkey')
    op.drop_constraint(None, 'model_attitudes', type_='foreignkey')
    op.drop_column('model_attitudes', 'right_attribute_id')
    op.drop_column('model_attitudes', 'left_attribute_id')
    # ### end Alembic commands ###
