apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "data-catalog.fullname" . }}-configmap
  labels:
    {{- include "data-catalog.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configmap }}
  dwh_data_catalog_{{ $key }}: {{ $value | quote }}
  {{- end }}