apiVersion: v1
kind: Secret
metadata:
  name: {{ template "data-catalog.fullname" . }}-secret
  labels:
    {{- include "data-catalog.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.secrets }}
  dwh_data_catalog_{{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
type: Opaque