apiVersion: v1
kind: Secret
metadata:
  name: {{ template "data-catalog.fullname" . }}-secret
  labels:
    {{- include "data-catalog.labels" . | nindent 4 }}
data:
  dwh_data_catalog_neo4j_connection_string: {{ .Values.secrets.dc_neo4j_connection_string }}
  dwh_data_catalog_neo4j_connection_user: {{ .Values.secrets.dc_neo4j_connection_user | b64enc }}
  dwh_data_catalog_neo4j_connection_password: {{ .Values.secrets.dc_neo4j_connection_password | b64enc }}
type: Opaque