apiVersion: v1
kind: Secret
metadata:
  name: {{ include "data-catalog.fullname" . }}-secret
  labels:
    {{- include "iam.labels" . | nindent 4 }}
data:
  dwh_data_catalog_neo4j_connection_string: {{ .Values.secrets.dc_neo4j_connection_string }}
type: Opaque